from .config import *
from .utils import make_executable


def generate_rename_script(class_list, workspace=None):
    """Generate the rename_windows.sh script with optional workspace filter."""
    classes_str = ' '.join([f"'{c}'" for c in class_list])

    # workspace placeholder is inserted literally; we will write the bash snippet accordingly
    workspace_cond = ''
    if workspace is not None:
        # workspace is a string like '0' from combo data
        workspace_cond = f"if [[ \"$WS_NUM\" == \"{workspace}\" ]]; then\n            WINDOWS+=(\"$WID\")\n        fi"

    # Bash script: carefully include braces and quoting
    script = f"""#!/bin/bash
# Auto-generated by Dofus Window Manager

CLASS_INI=({classes_str})

# Get all Dofus windows with optional workspace filter
mapfile -t ALL_LINES < <(wmctrl -l)
WINDOWS=()
for line in "${{ALL_LINES[@]}}"; do
    WID=$(echo "$line" | awk '{{print $1}}')
    WS_NUM=$(echo "$line" | awk '{{print $2}}')
    TITLE=$(echo "$line" | awk '{{for(i=4;i<=NF;i++) printf $i " "; print ""}}' | sed 's/ *$//')

    if [[ "$TITLE" =~ ^Dofus- ]]; then
        {('' if workspace is None else 'if [[ "$WS_NUM" == "' + str(workspace) + '" ]]; then')}
            WINDOWS+=("$WID")
        {('' if workspace is None else 'fi')}
    fi
done

if (( ${{#WINDOWS[@]}} != ${{#CLASS_INI[@]}} )); then
    notify-send "Dofus Manager" "⚠️ Window count (${{#WINDOWS[@]}}) ≠ classes (${{#CLASS_INI[@]}})"
    exit 1
fi

# Rename windows in order
for i in "${{!CLASS_INI[@]}}"; do
    wid=${{WINDOWS[$i]}}
    name=${{CLASS_INI[$i]}}
    wmctrl -i -r "$wid" -N "Dofus-$name"
done

notify-send "Dofus Manager" "✅ Windows renamed"
"""

    RENAME_SCRIPT.write_text(script)
    make_executable(RENAME_SCRIPT)


def generate_cycle_forward(class_list):
    classes_str = ' '.join([f"'{c}'" for c in class_list])
    script = f"""#!/bin/bash
# Auto-generated by Dofus Window Manager

CLASS_INI=({classes_str})
STATE_FILE="/tmp/dofus_window_index"
LAST_WINDOW_FILE="/tmp/dofus_last_window"

AVAILABLE=($(wmctrl -l | grep "Dofus-" | awk '{{print $NF}}' | cut -d'-' -f2))

if [[ ${{#AVAILABLE[@]}} -eq 0 ]]; then
    exit 1
fi

INDEX=0
[ -f "$STATE_FILE" ] && INDEX=$(cat "$STATE_FILE")

TOTAL=${{#CLASS_INI[@]}}
for ((i=1; i<=TOTAL; i++)); do
    NEXT=$(( (INDEX + i) % TOTAL ))
    CLASS_NAME=${{CLASS_INI[$NEXT]}}

    if printf '%s\\n' "${{AVAILABLE[@]}}" | grep -q "^$CLASS_NAME$"; then
        TARGET="Dofus-$CLASS_NAME"

        if [ -f "$LAST_WINDOW_FILE" ] && [ "$(cat $LAST_WINDOW_FILE)" = "$TARGET" ]; then
            exit 0
        fi

        wmctrl -a "$TARGET"
        echo "$NEXT" > "$STATE_FILE"
        echo "$TARGET" > "$LAST_WINDOW_FILE"
        exit 0
    fi
done
"""
    CYCLE_FORWARD.write_text(script)
    make_executable(CYCLE_FORWARD)


def generate_cycle_backward(class_list):
    classes_str = ' '.join([f"'{c}'" for c in class_list])
    script = f"""#!/bin/bash
# Auto-generated by Dofus Window Manager

CLASS_INI=({classes_str})
STATE_FILE="/tmp/dofus_window_index"

AVAILABLE=($(wmctrl -l | grep "Dofus-" | awk '{{print $NF}}' | cut -d'-' -f2))

if [[ ${{#AVAILABLE[@]}} -eq 0 ]]; then
    exit 1
fi

INDEX=0
[ -f "$STATE_FILE" ] && INDEX=$(cat "$STATE_FILE")

TOTAL=${{#CLASS_INI[@]}}
for ((i=1; i<=TOTAL; i++)); do
    NEXT=$(( (INDEX - i + TOTAL) % TOTAL ))
    CLASS_NAME=${{CLASS_INI[$NEXT]}}

    if printf '%s\\n' "${{AVAILABLE[@]}}" | grep -q "^$CLASS_NAME$"; then
        wmctrl -a "Dofus-$CLASS_NAME"
        echo "$NEXT" > "$STATE_FILE"
        exit 0
    fi
done
"""
    CYCLE_BACKWARD.write_text(script)
    make_executable(CYCLE_BACKWARD)


def generate_toggle_workspace():
    script = """#!/bin/bash
# Auto-generated by Dofus Window Manager

# Get total number of workspaces
TOTAL_WS=$(wmctrl -d | wc -l)

# Get current workspace
CURRENT_WS=$(wmctrl -d | grep '*' | awk '{print $1}')

# Calculate next workspace (cycle)
NEXT_WS=$(( (CURRENT_WS + 1) % TOTAL_WS ))

# Switch to next workspace
wmctrl -s $NEXT_WS
"""
    TOGGLE_WORKSPACE.write_text(script)
    make_executable(TOGGLE_WORKSPACE)

def generate_click_cycle():
    """Generate a script that simulates a left click and cycles windows"""
    script = f"""#!/bin/bash
# Auto-generated by Dofus Window Manager

# Simulate left click at current mouse position
xdotool click 1

# Execute the cycle forward script
"{CYCLE_FORWARD}"
"""
    CLICK_CYCLE = SCRIPT_DIR / "click_cycle_forward.sh"
    CLICK_CYCLE.write_text(script)
    make_executable(CLICK_CYCLE)