from .config import *
from .utils import make_executable


def generate_rename_script(class_list, workspace=None):
    """Generate the rename_windows.sh script with optional workspace filter."""
    classes_str = ' '.join([f"'{c}'" for c in class_list])

    # Workspace filter for script
    if workspace is not None:
        workspace_line = f'TARGET_WS={workspace}'
    else:
        workspace_line = 'TARGET_WS=$(wmctrl -d | awk \'/*/ {print $1}\')'

    script = f"""#!/bin/bash
# Auto-generated by Dofus Window Manager

CLASS_LOGIN=({classes_str})
WIN_EXCLUS="Dofus-{class_list[0]}"  # First class is not muted

# Workspace to rename
{workspace_line}

# Windows in the workspace
WINDOWS=($(wmctrl -l | awk -v ws="$TARGET_WS" '$2 == ws && /Dofus($|-)/ {{print $1}}'))

if [[ ${{#WINDOWS[@]}} -eq 0 ]]; then
    echo "No windows in workspace $TARGET_WS."
    exit 0
fi

echo "Windows in workspace $TARGET_WS: ${{#WINDOWS[@]}}"

# Rename windows
COUNT=0
for WIN_ID in "${{WINDOWS[@]}}"; do
    CLASS_NAME="${{CLASS_LOGIN[$COUNT]}}"
    if [[ -n "$CLASS_NAME" ]]; then
        wmctrl -ir "$WIN_ID" -N "Dofus-$CLASS_NAME"
        echo "Window renamed: Dofus-$CLASS_NAME"
    else
        echo "Not enough names in CLASS_LOGIN to rename all windows."
        break
    fi
    COUNT=$((COUNT+1))
done

echo "Rename ended."

# Mute all Dofus windows except WIN_EXCLUS
wmctrl -l | grep "Dofus-" | grep -v "$WIN_EXCLUS" | while read -r LINE; do
    WIN_ID=$(echo "$LINE" | awk '{{print $1}}')
    PID=$(xprop -id "$WIN_ID" _NET_WM_PID | awk '{{print $3}}')
    
    if [[ -n "$PID" ]]; then
        # Mute sink-inputs matching the PID
        pactl list sink-inputs | \\
        awk "/Sink Input/ {{entry=\\$0}} /application.process.id = \\"$PID\\"/ {{print entry}}" | \\
        grep "Sink Input" | while read -r ENTRY; do
            INPUT_ID=$(echo "$ENTRY" | grep -oE '[0-9]+')
            pactl set-sink-input-mute "$INPUT_ID" 1
            echo "Window muted: $WIN_ID (PID $PID, Sink $INPUT_ID)"
        done
    fi
done

echo "Muting ended."
"""

    RENAME_SCRIPT.write_text(script)
    make_executable(RENAME_SCRIPT)




def generate_cycle_forward(class_list):
    """Generate cycle forward script - FIXED to match original"""
    classes_str = ' '.join([f"'{c}'" for c in class_list])
    script = f"""#!/bin/bash
# Auto-generated by Dofus Window Manager

CLASS_INI=({classes_str})
STATE_FILE="/tmp/dofus_window_index"

# FIXED: Use $4 instead of $NF to match original behavior
AVAILABLE=($(wmctrl -l | grep "Dofus-" | awk '{{print $4}}' | cut -d'-' -f2))

if [[ ${{#AVAILABLE[@]}} -eq 0 ]]; then
    echo "No window detected."
    exit 1
fi

# Previous index or start at 0
if [ -f "$STATE_FILE" ]; then
    INDEX=$(cat "$STATE_FILE")
else
    INDEX=0
fi

# Search for next index CLASS_INI
TOTAL=${{#CLASS_INI[@]}}
for ((i=1; i<=TOTAL; i++)); do
    NEXT=$(( (INDEX + i) % TOTAL ))
    CLASS_NAME=${{CLASS_INI[$NEXT]}}
    if printf '%s\\n' "${{AVAILABLE[@]}}" | grep -q "^$CLASS_NAME$"; then
        wmctrl -a "Dofus-$CLASS_NAME"
        echo "$NEXT" > "$STATE_FILE"
        echo "Switch to Dofus-$CLASS_NAME"
        exit 0
    fi
done

echo "No windows has been found."
"""
    CYCLE_FORWARD.write_text(script)
    make_executable(CYCLE_FORWARD)


def generate_cycle_backward(class_list):
    """Generate cycle backward script - FIXED to match original"""
    classes_str = ' '.join([f"'{c}'" for c in class_list])
    script = f"""#!/bin/bash
# Auto-generated by Dofus Window Manager

CLASS_INI=({classes_str})
STATE_FILE="/tmp/dofus_window_index"

# FIXED: Use $4 instead of $NF
AVAILABLE=($(wmctrl -l | grep "Dofus-" | awk '{{print $4}}' | cut -d'-' -f2))

if [[ ${{#AVAILABLE[@]}} -eq 0 ]]; then
    echo "No window detected."
    exit 1
fi

# Previous index or start at 0
if [ -f "$STATE_FILE" ]; then
    INDEX=$(cat "$STATE_FILE")
else
    INDEX=0
fi

# Search for next index CLASS_INI
TOTAL=${{#CLASS_INI[@]}}
for ((i=1; i<=TOTAL; i++)); do
    NEXT=$(( (INDEX - i + TOTAL) % TOTAL ))
    CLASS_NAME=${{CLASS_INI[$NEXT]}}
    if printf '%s\\n' "${{AVAILABLE[@]}}" | grep -q "^$CLASS_NAME$"; then
        wmctrl -a "Dofus-$CLASS_NAME"
        echo "$NEXT" > "$STATE_FILE"
        echo "Switch to Dofus-$CLASS_NAME"
        exit 0
    fi
done

echo "No windows has been found."
"""
    CYCLE_BACKWARD.write_text(script)
    make_executable(CYCLE_BACKWARD)


def generate_toggle_workspace():
    """Generate toggle workspace script - simplified version"""
    script = """#!/bin/bash
# Auto-generated by Dofus Window Manager

# Current workspace, start at 0
CURRENT_WS=$(wmctrl -d | awk '$2 == "*" {print $1}')

if [ "$CURRENT_WS" -eq 0 ]; then
    wmctrl -s 1
else
    wmctrl -s 0
fi
"""
    TOGGLE_WORKSPACE.write_text(script)
    make_executable(TOGGLE_WORKSPACE)


def generate_click_cycle():
    """Generate a script that simulates a left click and cycles windows"""
    script = f"""#!/bin/bash
# Auto-generated by Dofus Window Manager

# Left click
xdotool click 1

# Cycle through Dofus windows
"{CYCLE_FORWARD}"
"""
    CLICK_CYCLE_FORWARD.write_text(script)
    make_executable(CLICK_CYCLE_FORWARD)